version: "3"

services:
  client:
    build: 
        context: ./client
        target: "builder"
    working_dir: /client
    ports:
      - 80:3000
    environment:
      - HOST=0.0.0.0
      - NUXT_APP_BACK_HOST

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: development
    tty: true
    volumes:
      - type: bind
        source: ./server
        target: /server
    working_dir: /server
    command: python main.py
    environment:
      FLASK_ENV: development
      FLASK_APP: app
      FLASK_RUN_PORT: 8080
    ports:
      - "8081:8080"
    restart: always
