version: "3"

services:
  client:
    build:
      context: ./client
      target: "development"
    volumes:
      - ./client:/client
      - npm-cache:/client/node_modules
      - nuxt-cache:/client/.nuxt
    ports:
      - "3000:3000"
    working_dir: /client
    command: sh -c "yarn && yarn dev"
    environment:
      - HOST=0.0.0.0

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: development
    tty: true
    volumes:
      - type: bind
        source: ./server
        target: /server
    working_dir: /server
    command: python main.py
    environment:
      FLASK_ENV: development
      FLASK_APP: app
      FLASK_RUN_PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: test
      DB_USER: root
      DB_PASS: root_password
    ports:
      - "8081:8080"
    depends_on:
      - db
    restart: always

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      MYSQL_DATABASE: test
      # MYSQL_USER: test
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      # - ./db:/docker-entrypoint-initdb.d
      # - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "13036:3036"
    # restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
        - "13306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: dena-hackathon-swagger
    environment:
      API_URL: api-document.yml
    volumes:
      - ./api-document.yml:/usr/share/nginx/html/api-document.yml
    ports:
      - 127.0.0.1:80:8080

volumes:
  db_data:
  npm-cache:
  nuxt-cache:
