"""“init”

Revision ID: a5a91978daa5
Revises: 
Create Date: 2021-09-19 03:58:50.478565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from app.models.columntypes import Geometry

# revision identifiers, used by Alembic.
revision = 'a5a91978daa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('username', mysql.VARCHAR(
                        length=50), nullable=False),
                    sa.Column('latlng', Geometry(2, 4326), nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=False),
                    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('locus',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', mysql.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=False),
                    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.id'], name='locus_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )

    op.create_table('geo',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', mysql.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('latlng', Geometry(2, 4326), nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=False),
                    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.id'], name='geo_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )

    op.create_index('latest_user_geo_idx', 'geo', [
        'created_at', 'user_id'], unique=False)

    op.create_table('locusNotify',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('locus_id', mysql.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('victim_user_id', mysql.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('is_checked', mysql.SMALLINT(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=False),
                    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['locus_id'], ['locus.id'], name='locusNotify_ibfk_2'),
                    sa.ForeignKeyConstraint(['victim_user_id'], [
                        'user.id'], name='locusNotify_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locusNotify')
    op.drop_table('geo')
    op.drop_index('latest_user_geo_idx', table_name='geo')
    op.drop_table('locus')
    op.drop_table('user')
# ### end Alembic commands ###
